### ISSUE TITLE
Page trim

### ISSUE THREAD

**Issue by jiuguangw** [JenniferMack/latex-kdp#2]
I'm using
`\documentclass[800paper,12pt,openright,twoside]{kdp}`
`\usepackage{geometry}`
but the resulting page doesn't look trimmed. The PDF file says 8x10 but the margins look huge. I think I must not be using the geometry package correctly or the margin settings are screwed up somehow. Any ideas?

Thanks.

**Comment by JenniferMack** [comment]
You're over specifying, try just 
```
\documentclass[800paper]{kdp}
```

**Comment by jiuguangw** [comment]
That didn't work. I believe the margin settings are correct in your style file - for my document, I get 634 pages as the output using your style file, vs. 638 pages when I manually specify the margins via the geometry package. However, using your style file + `\usepackage{geometry}`, the outter page trim is incorrect - I get a huge amount of white space, especially on the bottom, below the page number.

I'm using LuaTeX-1.12.0 on macOS.
